In [1]:
import math 
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt

# Solve $A \boldsymbol{x} = \boldsymbol{b}$ where
$$A = \begin{bmatrix} 4 & -1 & 0 & 0 & \cdots & 0 \\ -1 & 4 & -1 & 0 & \cdots & 0 \\ 
0 & -1 & 4 & -1 & \cdots & 0 \\ \vdots & \ddots & \ddots & \ddots & \ddots & \vdots \\ 
0 & \cdots & -1 & 4 & -1 & 0 \\ 
0 & \cdots & 0 & -1 & 4 & -1 \\
0 & \cdots & 0 & 0 & -1 & 4 \end{bmatrix}$$

In [2]:
def example_strict_diag (n,d):
    A = d*np.identity(n)
    A[0,1] = -1.
    A[n-1,n-2] = -1.
    for i in range (1,n-1):
        A[i,i-1] = -1
        A[i,i+1] = -1
    return A

# Solve the linear system for several different $n$ values.
## What do you observe?

In [11]:
n = 100
d = 4
A = example_strict_diag(n,d)
x = np.random.randint(1,3,n)*(1.) # pick a random solution vector
b = A @ x # the corresponding right hand side
%time x_gauss = linalg.solve(A,b)
print (linalg.norm(x-x_gauss))
print (x[0:10],' ',x_gauss[0:10])
#print(A)

Wall time: 993 µs
4.1540741810552243e-16
[1. 1. 2. 2. 1. 2. 2. 2. 2. 2.]   [1. 1. 2. 2. 1. 2. 2. 2. 2. 2.]


# Solve for $n = 20000$.  It takes a long time!

In [12]:
n = 20000
d = 4
A = example_strict_diag(n,d)
x = np.random.randint(1,3,n)*(1.) # pick a random solution vector
b = A @ x # the corresponding right hand side
%time x_gauss = linalg.solve(A,b)
print (linalg.norm(x-x_gauss))
print (x[0:10],' ',x_gauss[0:10])

Wall time: 1min 15s
4.002966042486721e-16
[1. 1. 1. 2. 1. 1. 1. 1. 1. 2.]   [1. 1. 1. 2. 1. 1. 1. 1. 1. 2.]


## Multiplying an $n \times n$ matrix $A$ by a vector $\vec{x}$ takes how many steps?

## Answer : 

## Consider again our matrix 

$$A = \begin{bmatrix} 4 & -1 & 0 & 0 & \cdots & 0 \\ -1 & 4 & -1 & 0 & \cdots & 0 \\ 
0 & -1 & 4 & -1 & \cdots & 0 \\ \vdots & \ddots & \ddots & \ddots & \ddots & \vdots \\ 
0 & \cdots & -1 & 4 & -1 & 0 \\ 
0 & \cdots & 0 & -1 & 4 & -1 \\
0 & \cdots & 0 & 0 & -1 & 4 \end{bmatrix}$$

## The matrix $A$ is called a *tridiagonal* matrix.  

## It is an example of a *sparse* matrix (entries are mostly $0$).  

## Multiplying an $n \times n$ tridiagonal matrix by a vector $\vec{x}$ takes how many steps?

## Answer :

# The Jacobi Solver Iteration for solving $A \boldsymbol{x} = \boldsymbol{b}$ is 
$$\boldsymbol{x}_{k+1} = D^{-1}(D - A) \boldsymbol{x}_k + D^{-1} \boldsymbol{b}$$
## The most expensive operation is the matrix-vector multiplication 
$$D^{-1}(D - A) \boldsymbol{x}_k$$

## Again consider our matrix 
$$A = \begin{bmatrix} 4 & -1 & 0 & 0 & \cdots & 0 \\ -1 & 4 & -1 & 0 & \cdots & 0 \\ 
0 & -1 & 4 & -1 & \cdots & 0 \\ \vdots & \ddots & \ddots & \ddots & \ddots & \vdots \\ 
0 & \cdots & -1 & 4 & -1 & 0 \\ 
0 & \cdots & 0 & -1 & 4 & -1 \\
0 & \cdots & 0 & 0 & -1 & 4 \end{bmatrix}$$
It is not hard to show (exercise!) that 

$$T = D^{-1} (D-A) = \begin{bmatrix} 0 & 1/4 & 0 & 0 & \cdots & 0 \\ 1/4 & 0 & 1/4 & 0 & \cdots & 0 \\ 
0 & 1/4 & 0 & 1/4 & \cdots & 0 \\ \vdots & \ddots & \ddots & \ddots & \ddots & \vdots \\ 
0 & \cdots & 1/4 & 0 & 1/4 & 0 \\ 
0 & \cdots & 0 & 1/4 & 0 & 1/4 \\
0 & \cdots & 0 & 0 & 1/4 & 0 \end{bmatrix}$$

## The matrices $A$ and $T$ are called *tridiagonal* matrices.  

## They are examples of *sparse* matrices (entries are mostly $0$).  

## Multiplying an arbitrary $n \times n$ matrix $A$ by a vector $\vec{x}$ in $\mathbb{R}^n$ takes roughly how many operations?

## Answer : 


## Multiplying a $n \times n$ tridiagonal matrix by a vector $\vec{x}$ takes roughly how many operations?

## Answer :

## In addition, it takes much less memory to store a tridiagonal matrix!

## Here is a function that creates $T = D^{-1} (D-A)$ using only $3n$ storage and a function for efficiently multiplying a tridiagonal matrix by a vector $\vec{x}$.

In [48]:
def example_strict_tri_diag_T (n,d):
    T = np.zeros ([n,3])
    T[0,0] = 0
    T[0,1] = 1/d
    T[n-1,1] = 1/d
    T[n-1,2] = 0
    for i in range (1,n-1):
        T[i,0] = 1/d
        T[i,1] = 0
        T[i,2] = 1/d
    return T
#print(T)
def tri_mult (T,x):
    result = np.zeros(n)
    result[0] = T[0,0]*x[0] + T[0,1]*x[1]
    result[n-1] = T[n-1,1]*x[n-2] + T[n-1,2]*x[n-1]
    for i in range (1,n-1):
        result[i] = T[i,0]*x[i-1] + T[i,1]*x[i] + T[i,2]*x[i+1]
    return result

# Solve the linear system using the Jacobi Solver Iteration for $n = 20000$ (with the $x$ and $b$ vectors generated above).

# What do you observe?

In [16]:
num_iter = 50 # while loop with a stopping condition would be better!
d = 4
T = example_strict_tri_diag_T(n,d)
c = b/d # Note that c = T^{-1} b = b/4
x_jacobi = np.zeros(n)
%time for i in range(0,num_iter): x_jacobi = tri_mult(T,x_jacobi) + c
print (linalg.norm(x-x_jacobi))
print (x[0:10],' ',x_jacobi[0:10])

Wall time: 37.1 s
0.0
[1. 1. 1. 2. 1. 1. 1. 1. 1. 2.]   [1. 1. 1. 2. 1. 1. 1. 1. 1. 2.]


# Class Exercise 1 : Solve $A \boldsymbol{x} = \boldsymbol{b}$ where
$$A = \begin{bmatrix} 2 & -1 & 0 & 0 & \cdots & 0 \\ -1 & 2 & -1 & 0 & \cdots & 0 \\ 
0 & -1 & 2 & -1 & \cdots & 0 \\ \vdots & \ddots & \ddots & \ddots & \ddots & \vdots \\ 
0 & \cdots & -1 & 2 & -1 & 0 \\ 
0 & \cdots & 0 & -1 & 2 & -1 \\
0 & \cdots & 0 & 0 & -1 & 2 \end{bmatrix}$$

# Part 1 : Run the codes below.  

* What do you observe?  
* What can you do to reduce the error for the Jacobi Solver Iteration? 
* About how many iterations are required to get an error near 0.01?

In [34]:
n = 100
d = 2
A = example_strict_diag(n,d)
x = np.random.randint(1,3,n)*(1.) # pick a random solution vector
b = A @ x # the corresponding right hand side
%time x_gauss = linalg.solve(A,b)
print (linalg.norm(x-x_gauss))
print (x[0:10],' ',x_gauss[0:10])

Wall time: 1.9 ms
1.4001030442774933e-13
[1. 1. 1. 1. 2. 2. 1. 2. 1. 1.]   [1. 1. 1. 1. 2. 2. 1. 2. 1. 1.]


In [31]:
num_iter = 14700 # while loop with a stopping condition would be better!
d = 2
T = example_strict_tri_diag_T(n,d)
c = b/d # Note that c = T^{-1} b = b/2
x_jacobi = np.zeros(n)
%time for i in range(0,num_iter): x_jacobi = tri_mult(T,x_jacobi) + c
print (linalg.norm(x-x_jacobi))
print (x[0:10],' ',x_jacobi[0:10])

Wall time: 2.79 s
0.010625862249419655
[2. 1. 1. 1. 2. 1. 2. 1. 2. 1.]   [1.99995307 0.99990791 0.99985938 0.99981618 1.99976624 0.99972515
 1.999674   0.9996352  1.99958302 0.99954665]


In [ ]:
# need to run about 14500 times for error to be near 0.01

# Part 2 : Using a combination of Python and math, explain what is going on.  In particular, why is the convergence of the Jacobi Solver Iteration so slow.  What conclusions can you draw?

## Hint : Carefully consider the matrix $T = D^{-1}(D - A)$.

In [56]:
n = 100
d = 4
D = np.diag(np.diag(D))
#print(D)
A = example_strict_diag(n,d)
T = linalg.inv(D) @ (D - A)
max(abs(linalg.eig(T)[0]))
T = (np.diag(np.diag(A)) - A)
D_inv= np.linalg.inv(D)
D_inv

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

# Part 3 : Calculate $\rho(D^{-1}(D-A))$ for $n = 50, 100, 150, 200$.  What do you observe?  What does this tell you about the prospect of using the Jacobi Solver Iteration for solving this system for large $n$?