In [2]:
import math 
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt
np.set_printoptions(suppress=True)

# Givens Rotation Matrix

In [3]:
# Inputs
# A : n x n symmetric matrix (A.T = A)
# p,q : row and column to zero out
# Outputs
# U : Orthogonal Matrix such that (U^T A U)_pq = (U^T A U)_qp = 0
def givens_rotation (A,p,q):
    U = np.identity(len(A))
    if (A[p,q] != 0):
        temp = (A[p,p] - A[q,q])/A[p,q]
        root = (temp + math.sqrt(temp**2+4))/2
        c = 1/math.sqrt(1+root**2)
        s = c*root
        U[p,p] = c
        U[p,q] = s
        U[q,p] = -s
        U[q,q] = c
    return (U)

# Example 1 
# $$A = \begin{bmatrix} 1 & 2 \\ 2 & 1 \end{bmatrix}$$

In [ ]:
A = np.array([[1,2],[2,1]])
print (A)
print(linalg.eig(A)[0])

In [ ]:
U = givens_rotation (A,0,1)
print (U,'\n\n',U.T @ U)

In [ ]:
D = U.T @ A @ U
print (D)

In [ ]:
print (U @ D @ U.T)

# Example 2 
# $$A = \begin{bmatrix} 1 & 0 & -1 \\ 0 & 1 & 0 \\ -1 & 0 & 1  \end{bmatrix}$$

In [ ]:
A = np.array([[1,0,-1],[0,1,0],[-1,0,1]])
print (A)
print(linalg.eig(A)[0])

In [ ]:
U = givens_rotation (A,0,2)
print (U,'\n\n',U.T @ U)

In [ ]:
D = U.T @ A @ U
print (D)

In [ ]:
print (U @ D @ U.T)

# Example 3 
# $$A = \begin{bmatrix} 2 & 3 & 0 \\ 3 & 2 & 4 \\ 0 & 4 & 2 \end{bmatrix}$$

In [3]:
A = np.array([[2,3,0],[3,2,4],[0,4,2]])
print (A)
print(linalg.eig(A)[0])

[[2 3 0]
 [3 2 4]
 [0 4 2]]
[ 7.+0.j  2.+0.j -3.+0.j]


In [1]:
U = givens_rotation (A,1,2)
print (U,'\n\n',U.T @ U)

NameError: name 'givens_rotation' is not defined

In [7]:
D = U.T @ A @ U
print (D)

[[ 2.          2.12132034  2.12132034]
 [ 2.12132034 -2.          0.        ]
 [ 2.12132034  0.          6.        ]]


In [8]:
U = U @ givens_rotation (D,0,1)
print (U,'\n\n',U.T @ U)

[[ 0.39623583  0.91814877  0.        ]
 [-0.64922922  0.28018104  0.70710678]
 [ 0.64922922 -0.28018104  0.70710678]] 

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
D = U.T @ A @ U
print (D)

[[-2.91547595 -0.          0.84054312]
 [-0.          2.91547595  1.94768767]
 [ 0.84054312  1.94768767  6.        ]]


In [11]:
U = U @ givens_rotation (D,1,2)
D = U.T @ A @ U
print (D)

[[-2.91547595 -0.7566727  -0.36600431]
 [-0.7566727   6.94210096  0.        ]
 [-0.36600431  0.          1.97337499]]


In [12]:
U = U @ givens_rotation (D,0,2)
D = U.T @ A @ U
print (D)

[[ 2.00062406 -0.0561789   0.        ]
 [-0.0561789   6.94210096 -0.75458433]
 [ 0.         -0.75458433 -2.94272502]]


In [13]:
U = U @ givens_rotation (D,0,1)
D = U.T @ A @ U
print (D)

[[ 6.94273956  0.          0.75453558]
 [ 0.          1.99998546 -0.00857709]
 [ 0.75453558 -0.00857709 -2.94272502]]


In [14]:
U = U @ givens_rotation (D,0,2)
D = U.T @ A @ U
print (D)

[[-2.99998537  0.0085525  -0.        ]
 [ 0.0085525   1.99998546 -0.00064903]
 [-0.         -0.00064903  6.99999992]]


In [15]:
U = U @ givens_rotation (D,1,2)
D = U.T @ A @ U
print (D)

[[-2.99998537  0.00000111  0.0085525 ]
 [ 0.00000111  7.          0.        ]
 [ 0.0085525   0.          1.99998537]]


In [16]:
U = U @ givens_rotation (D,0,2)
D = U.T @ A @ U
print (D)

[[-3.          0.00000111 -0.        ]
 [ 0.00000111  7.          0.        ]
 [-0.          0.          2.        ]]


In [17]:
print (U @ D @ U.T)

[[2. 3. 0.]
 [3. 2. 4.]
 [0. 4. 2.]]


# Example 4 
# $$A = \begin{bmatrix} 2 & 1 & 1 & -2 \\ 1 & 2 & 1 & 1 \\ 1 & 1 & 2 & 1 \\ -2 & 1 & 1 & 2 \end{bmatrix}$$

In [18]:
A = np.array([[2,1,1,-2],[1,2,1,1],[1,1,2,1],[-2,1,1,2]])
print (A,'\n\n',linalg.eig(A)[0])

[[ 2  1  1 -2]
 [ 1  2  1  1]
 [ 1  1  2  1]
 [-2  1  1  2]] 

 [ 4.+0.j -1.+0.j  4.+0.j  1.+0.j]


## Exercise 1 : Locate Maximum Off Diagonal Entry

In [31]:
# Inputs
# A : n x n symmetric matrix (A.T = A)
# Outputs
# max : maximum size off diagonal entry
# max_row, max_col : location of maximum size off diagonal entry
def locate_max (A):
    n = len(A)
    max_row = 0;
    max_col = 1;
    max = abs(A[max_row,max_col])
    # Add Nested For Loop here
    for(i = 0; i<n; i++){
        for(j=1; j<n; j++){
            temp = abs(A[i,j])
            if (temp > max){
                max = temp
            }
        }
    }
    return [max,max_row,max_col]

SyntaxError: invalid syntax (<ipython-input-31-7e6503c2624a>, line 12)

In [21]:
print (locate_max(A))

[1, 0, 1]


## Exercise 2 : Jacobi Eigenvalue Method

In [23]:
# Inputs
# A : n x n symmetric matrix (A.T = A)
# max_steps : Maximum Number of Iterations
# eps : Converges when all off diagonal entries of D have size <= eps
# Outputs
# flag : TRUE if successful and FALSE otherwise
# num : Number of Iterations
# D, U : If flag==TRUE, then D is diagonal, U^T U = I, and A = UDU^T
def jacobi_factor (A,max_steps,eps):
    n = len(A)
    D = A
    U = np.identity(n)
    num = 0
    [max,p,q] = locate_max(D)
    # Add While Loop Here
    return [max <= eps,num,D,U]

In [24]:
[flag,num,D,U] = jacobi_factor(A,1000,1e-6)

In [25]:
print (flag,num,'\n\n',D,'\n\n',U,'\n\n',U.T @ U,'\n\n',U @ D @ U.T)

False 0 

 [[ 2  1  1 -2]
 [ 1  2  1  1]
 [ 1  1  2  1]
 [-2  1  1  2]] 

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

 [[ 2.  1.  1. -2.]
 [ 1.  2.  1.  1.]
 [ 1.  1.  2.  1.]
 [-2.  1.  1.  2.]]
